package org.telosys.tools.nrt;

import java.util.regex.Pattern;

public class LineComparatorForGeneratedFiles implements LineComparator {
	
	private final static String[] patterns = {
		".* Created on .* Time .*",
		".* [Gg]enerated by Telosys Tools Generator .*",
		".*generator\\.version =.*",
		".*today\\.time.*=.*",
		".*today\\.date.*=.*",
		".*<p>This documentation has been generated by.*",
		".*Documentation generated by.*",
		
		// for ApplicationConfig.java (entities order is different)
		".*return.*Validator.*",
		".*Validator declaration for.*",
		".*import org\\.demo.*",
		".*public.*Validator beforeCreate.*Validator.*",
		".*conversionService\\.addConverter.*",
		".*Converter for the composite key in the.*entity.*",
		".*public.*KeyConverter.*KeyConverter.*",
		".*return.*new.*KeyConverter.*",
	};
	
	@Override
	public boolean consideredAsIdentical(String line1, String line2) {
		for ( String p : patterns ) {
			if ( matches(line1, line2, p) )  {
				return true ;
			}
		}
		return false ;
	}
	
	private boolean matches(String line1, String line2, String patternString) {
		
		Pattern pattern = Pattern.compile(patternString);
		if ( pattern.matcher(line1).matches() && pattern.matcher(line2).matches()) {
			return true ;
		}
		return false ;
	}
}
